name: Setup terraform with oidc
description: "This action sets up Terraform with OIDC"
inputs:
  terraform_version:
    description: "Terraform Version"
    required: true
  terraform_dir:
    description: "Working directory of terraform"
    required: true
  backend_role_arn:
    description: "AWS Role to assume"
    required: true
  backend_region:
    description: "S3 backend Region"
    required: true
  backend_state_bucket:
    description: "Terraform State Bucket"
    required: true
  backend_state_key:
    description: "Terraform State File Key"
    required: true
  backend_lockid_table:
    description: "Terraform Lockid table"
    required: true

runs:
  using: "composite"
  steps:
    - id: tf_setup
      name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
    - id: aws_auth
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ inputs.backend_region }}
        role-to-assume: ${{ inputs.backend_role_arn }}

    - id: tf_init
      name: Init Terraform
      working-directory: ${{ inputs.terraform_dir }}
      shell: bash
      run: |
        terraform init \
          -backend-config="bucket=${{ inputs.backend_state_bucket }}" \
          -backend-config="key=${{ inputs.backend_state_key }}" \
          -backend-config="region=${{ inputs.backend_region }}" \
          -backend-config="encrypt=true" \
          -backend-config="dynamodb_table=${{ inputs.backend_lockid_table }}"
