name: Setup ecr with oidc
description: "This action sets up AWS ECR with OIDC"
inputs:
  oidc_role_arn:
    description: "AWS Role to assume"
    required: true
  region:
    description: "AWS Region"
    required: true
  registry_account:
    description: "AWS ECR Registry account"
    required: false

outputs:
  registry:
    description: "Logged in Amazon ECR Registry"
    value: ${{ steps.consolidate.outputs.registry }}

runs:
  using: "composite"
  steps:
    - id: aws_auth
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ inputs.region }}
        role-to-assume: ${{ inputs.oidc_role_arn }}

    - id: login_self_ecr
      name: Login to AWS ECR
      if: ${{ inputs.registry_account == '' }}
      uses: aws-actions/amazon-ecr-login@v2
    
    - id: login_other_ecr
      name: Login to AWS ECR
      if: ${{ inputs.registry_account != '' }}
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registries: ${{ inputs.registry_account }}
    
    - id: consolidate
      name: Finalise Outputs
      shell: bash
      run: |
        echo "registry=${{ steps.login_self_ecr.outputs.registry || steps.login_other_ecr.outputs.registry }}" >> $GITHUB_OUTPUT
