name: "Get PR Info with Validation"
description: "Retrieve PR info and validate commit messages for squash merges."
inputs:
  github_token:
    description: "GitHub token for authentication"
    required: true
  pr_number:
    description: "Pull Request number (optional, from dispatch input)"
    required: false
outputs:
  pr_number:
    description: "The PR number extracted or provided."
    value: ${{ steps.consolidate.outputs.pr_number }}
  pr_hash:
    description: "The short commit hash of the PR."
    value: ${{ steps.consolidate.outputs.pr_hash }}
  tag:
    description: "Generated tag in the format <short_hash>_<pr_number>."
    value: ${{ steps.consolidate.outputs.tag }}
runs:
  using: "composite"
  steps:
    - id: handle_dispatch
      name: Handle Dispatch Event
      if: ${{ inputs.pr_number != '' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        # Handle Dispatch Event
        if [ "${{ inputs.pr_number }}" -eq 0 ]; then
          echo "Dispatch input is 0. The default behaviour should be triggered."
          PR_NUMBER=0
          PR_HASH="default"
        else
          echo "Dispatch input is ${{ inputs.pr_number }}. Retrieving pull request commit hash."
          PR_NUMBER=${{ inputs.pr_number }}
          PR_HASH=$(gh pr view $PR_NUMBER --json mergeCommit --jq '.mergeCommit.oid' || exit 1)
          PR_HASH=$(git rev-parse --short $PR_HASH)
        fi
        echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
        echo "pr_hash=$PR_HASH" >> $GITHUB_OUTPUT

    - id: handle_push
      name: Handle Push Event
      if: ${{ inputs.pr_number == '' }}
      shell: bash
      run: |
        # Handle Push Event
        echo "Validating current head commit message"
        COMMIT_MESSAGE=$(git log -1 --pretty=%B | head -n 1)
        PR_NUMBER=$(echo "$COMMIT_MESSAGE" | grep -oP '\(#\K\d+')

        if [ -z "$PR_NUMBER" ]; then
          echo "Error: Commit message does not follow squash merge pattern, aborting..."
          exit 1
        fi

        PR_HASH=$(git rev-parse --short HEAD)
        echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
        echo "pr_hash=$PR_HASH" >> $GITHUB_OUTPUT

    - id: generate_tag
      name: Generate Tag
      shell: bash
      run: |
        TAG="${{ steps.handle_dispatch.outputs.pr_hash || steps.handle_push.outputs.pr_hash }}_${{ steps.handle_dispatch.outputs.pr_number || steps.handle_push.outputs.pr_number }}"
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - id: consolidate
      name: Finalize Outputs
      shell: bash
      run: |
        echo "pr_number=${{ steps.handle_dispatch.outputs.pr_number || steps.handle_push.outputs.pr_number }}" >> $GITHUB_OUTPUT
        echo "pr_hash=${{ steps.handle_dispatch.outputs.pr_hash || steps.handle_push.outputs.pr_hash }}" >> $GITHUB_OUTPUT
        echo "tag=${{ steps.generate_tag.outputs.tag }}" >> $GITHUB_OUTPUT
